pypro/aperitivos/urls.py
from django.urls import path
from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path
from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        # extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.User.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.shortcuts import render
from django.urls import reverse


class Video():
    def __init__(self, slug, titulo, vimeo_id):
        self.slug = slug
        self.titulo = titulo
        self.vimeo_id = vimeo_id

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug, ))


videos = [
    Video('motivacao', 'Vídeo Aperitivo: Motivação', 424506328),
    Video('instalacao-windows', 'Instalação Windows', 424506328),
]

videos_dct = {v.slug: v for v in videos}


def indice(request):
    return render(request,
                  'aperitivos/indice.html',
                  context={'videos': videos})


def video(request, slug):
    video = videos_dct[slug]
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro - Aperitivos{% endblock title %}
{% block description %}Página com todos os vídeos gratuitos{% endblock description %}

{% block body%}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">Lista de Vídeos Aperitivos</h1>
                <ol>
                    {% for video in videos %}
                        <li><a href="{{video.get_absolute_url}}"> {{video.titulo | default:"Faltando Título"}}</a></li>
                    {%empty%}
                        <li>Não foi encontrado nenhum vídeo de aperitivo</li>
                    {%endfor%}
                </ol>
            </div>
        </div>        
    </div>
{% endblock body%}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro - Aperitivo{% endblock title %}
{% block description %}Página desenvolvida para aprendizado de Django no curso Python Pro - Exemplo de vídeo de conteúdo{% endblock description %}

{% block body%}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">{{ video.titulo | default:"Faltando Título" }}</h1>
                <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
            </div>
        </div>        
    </div>
{% endblock body%}

pypro/base/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página desenvolvida para aprendizado de Django no curso Python Pro{% endblock description %}" />
    <meta name="author" content="Francisco Bustamante - @chicolucio" />

    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto"></ul>
        </div>
    </nav>

    {% block body%}{% endblock body%}

    {% include 'base/footer.html' with contato_email='chicolucio@whatever.com' only %}
    
    
</body>

</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em contato</h3>
                <address>
                    +55 21 999-666-334
                    <br />
                    <a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pb-4">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now "Y" %} Python Pro. Todos os direitos
                    reservados.
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro - Home{% endblock title %}

{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>
                    Aprendendo Django - Curso Python Pro
                </h2>

                <h4 class="mt-4">Matrículas abertas</h4>
                <!-- INICIO DO BOTAO PAGSEGURO -->
                <a href="https://pag.ae/7W3GCMg9v/button" target="_blank" title="Pagar com PagSeguro"><img
                                                                                                          src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif"
                                                                                                          alt="Pague com PagSeguro - é rápido, grátis e seguro!" /></a>
                <!-- FIM DO BOTAO PAGSEGURO -->

                {% comment %}
                <h4 class="mt-4">Entre na lista de espera</h4>

                <form
                action="https://gmail.us18.list-manage.com/subscribe/post?u=af11cb9765048af8c17cc7a84&amp;id=e679c7961f"
                method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                class="form-row align-items-center" target="_blank" novalidate>
                <div class="form-row align-items-center">
                <div class="col-auto">
                <label class="sr-only" for="mce-EMAIL">Email:</label>
                <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"
                placeholder="exemplo@email.com" />
                </div>
                <div class="col-auto">
                <label class="sr-only" for="mce-FNAME">Email:</label>
                <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME"
                placeholder="Seu nome" />
                </div>

                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                <div style="position: absolute; left: -5000px;" aria-hidden="true">
                <input type="text" name="b_af11cb9765048af8c17cc7a84_e679c7961f" tabindex="-1"
                value="" />
                </div>

                <div class="col-auto">
                <input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe"
                class="btn btn-primary" />
                </div>
                </div>
                </form>
                {% endcomment %}

                <p class="mt-4">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pulvinar facilisis consequat.
                    Proin massa eros, commodo quis pretium nec, luctus vel urna. Nunc ultrices, leo eget varius
                    viverra, orci tortor feugiat lacus, vel auctor lectus purus et metus. Morbi euismod pharetra
                    massa, quis vulputate urna ullamcorper nec. Nam a porta metus. Aenean suscipit orci non leo
                    venenatis blandit. Integer ultricies sit amet risus vitae ullamcorper.
                    <a href="http://github.com/chicolucio" target="_blank" rel="noopener noreferrer">Chico Lucio</a>
                </p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <h5 class="card-header">
                    Mais detalhes sobre o instrutor
                </h5>
                <div class="card-body">
                    <p class="card-text">
                        <img src="{% static 'img/chicolucio.png' %}" alt="Imagem ChicoLucio"
                             class="img-thumbnail float-left mr-3" width="128" />
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pulvinar facilisis
                        consequat. Proin massa eros, commodo quis pretium nec, luctus vel urna. Nunc ultrices, leo
                        eget varius viverra, orci tortor feugiat lacus, vel auctor lectus purus et metus. Morbi
                        euismod pharetra massa, quis vulputate urna ullamcorper nec. Nam a porta metus. Aenean
                        suscipit orci non leo venenatis blandit. Integer ultricies sit amet risus vitae ullamcorper.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body%}